baseURL = "/"
languageCode = "en-us"
title = "sertoi"
theme = "kube"
description = "SerToi, la biblioteca de proyectos de Sergio Nogueiras"
Paginate = 4

[Params]
  RSSLink = "/index.xml"
  author = "newpixcom" # add your company name
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = "sergio.nogueiras.fernandez@gmail.com"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"
